language: node_js
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
env:
    - run=1
    - run=2
    - run=3
    - run=4

script: curl -sL http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/precise/InRelease
install: true
notifications:
    email: never

